### ISSUE TITLE
axel 2.5 does not remember the value of LDFLAGS at configure time

### ISSUE THREAD

**Issue by ryandesign** [eribertomota/axel#1]
axel 2.5 remembers and uses the value of CFLAGS that the user set at configure time, but not the value of LDFLAGS.

This is sufficient to fix it:

```
--- configure.orig	2015-11-01 16:48:49.000000000 -0600
+++ configure	2015-11-13 10:11:08.000000000 -0600
@@ -236,6 +230,7 @@
 
 echo "CFLAGS+=${AXEL_CFLAGS}" >> Makefile.settings
 echo "LFLAGS+=${AXEL_LFLAGS}" >> Makefile.settings
+echo "LDFLAGS+=${LDFLAGS}" >> Makefile.settings
 
 echo 'Configuration done:'
 if [ "$i18n" = "1" ]; then
```

The Makefile is already written to use the LDFLAGS variable.

**Comment by eribertomota** [comment]
Hi,

I changed the build system to autotools and I18N is default now. So, this issue is solved. d7ac55b

Thanks!

Eriberto
