### ISSUE TITLE
aclocal compilation errors for custom build locations

### ISSUE THREAD

**Issue by mridulmalpotra** [eribertomota/axel#11]
I'm currently running Ubuntu 15.10 and was trying to build the project in a custom user directory, but it gives me the following error:

`$ ./configure --prefix=/home/mty/dev/.build/axel/ > /dev/null && make`

`CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/mty/dev/axel/missing aclocal-1.14`
`/home/mty/dev/axel/missing: line 81: aclocal-1.14: command not found`
`WARNING: 'aclocal-1.14' is missing on your system. `
`         You should only need it if you modified 'acinclude.m4' or`
`         'configure.ac' or m4 files included by 'configure.ac'.`
`         The 'aclocal' program is part of the GNU Automake package:`
`         <http://www.gnu.org/software/automake>`
`         It also requires GNU Autoconf, GNU m4 and Perl in order to run:`
`        <http://www.gnu.org/software/autoconf>`
`         <http://www.gnu.org/software/m4/>`
`         <http://www.perl.org/>`
`Makefile:378: recipe for target 'aclocal.m4' failed`

I have not modified any configuration files apart from passing the parameter. Trying to find a fix, I looked around and found this suggestion from one user facing a similar issue in another project ([github.com/SIPp/sipp/issues/61](https://github.com/SIPp/sipp/issues/61)). The fix was simply to run:

`$ touch configure.ac aclocal.m4 configure Makefile.am Makefile.in`

after which compilation worked smoothly and installed properly. Why do you think this is happening?

**Comment by sdt** [comment]
Pull request #10 fixes this sort of problem.

@mridulmalpotra, could you try checking out [this branch](https://github.com/sdt/axel/tree/autotools-cleanup), and then running `./autogen.sh` and your custom configure command ?

**Comment by mridulmalpotra** [comment]
@sdt I can confirm that running `./autogen.sh` before the custom configure command from the `autotools-cleanup` branch helps axel to successfully run and compile.

**Comment by sdt** [comment]
Fixed in 1ab96e7509014da6494ea1d66a21681281e417f4
