### ISSUE TITLE
ERROR: Connection gone

### ISSUE THREAD

**Issue by eribertomota** [eribertomota/axel#22]
To reproduce:

`#` axel https://nm.debian.org/public/processes
Initializing download: https://nm.debian.org/public/processes
Connection gone.

Works fine with curl and wget.

Regards,

Eriberto

**Comment by sijad** [comment]
after calling `SSL_read`, `SSL_get_error` returns `SSL_ERROR_WANT_READ`
https://github.com/sijad/axel/commit/b906b30f2f7b2c2532e744f7a3598493266b346c can fixes the issue but not sure if it's good solution or not @sdt

**Comment by sdt** [comment]
Looks like a good fix to me - we use blocking reads, so there appears to be no problem using the auto-retry mode. Good stuff @sijad !

**Comment by eribertomota** [comment]
Very good @sijad! Thanks @sdt for merge!

@sijad, if you want still playing, there are some challenges in #18 (I think that segmentation faults are the priority for Axel and are light for a newcomer).

I will release a new version with this fix now.

Cheers,

Eriberto

**Comment by eribertomota** [comment]
The 2.10 building in Debian now... Very beautiful.

https://buildd.debian.org/status/package.php?p=axel&suite=unstable
