### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by sijad** [eribertomota/axel#3]
I'm working with Axel for years now, but sometimes I think Axel doesn't support `HTTPS`,
please current me if I'm wrong, but Axel fails to donwload over SSL sometimes
after take a quick look at source code I couldn't find any related code to it

**Comment by pan-long** [comment]
I have looked at the source code, axel only supports http and ftp for now. It checks the protocol by prefix, anything starts with 'f' it will use ftp, anything starts with 'h' it will just go for http. So, yea, just add in another protocol and it should work.

**Comment by eribertomota** [comment]
Thanks Pan,

Do you are able to do it and integrate the development team?

Regards,

Eriberto


2016-03-20 12:12 GMT-03:00 Pan Long <notifications@github.com>:

**Comment by sijad** [comment]
* Can Axel run by library like `curl` to download? and axel manage multi connection download?
* download and search for ftp protocol isn't outdated? does any body still use that?
I'm just asking

**Comment by pan-long** [comment]
@eribertomota hi, yea, I should be able to implement this feature. @sijad I like your idea, but the only thing I worried about is can we do multi connection management over curl? As if curl doesn't provide intermediate access to the tcp packages and instead, it does some process and store it in it's own format, that could be troublesome for us. Of course, we need to do some investigation on this.

**Comment by eribertomota** [comment]
Thanks Pan! Thank! I am glad for you help!

I added you as collaborator and you can push changes.

Cheers,

Eriberto


2016-03-20 22:50 GMT-03:00 Pan Long <notifications@github.com>:

**Comment by eribertomota** [comment]
Done by @sdt .  e1ebab0
