### ISSUE TITLE
Ignore SSL errors and continue

### ISSUE THREAD

**Issue by jsEveryDay** [eribertomota/axel#56]
As I see many people have issues with axel and https.
I have similar issues due to self signed certificate. 

What is the option for **axcel equivalent to wget --no-check-certificate** ?

Is there an option for axelrc to ignore or not verify SSL certificates by default?

**Comment by ismaell** [comment]
The `--insecure` / `-k` switch disables certificate verification.

**Comment by jsEveryDay** [comment]
Thanks,

Couldn't find it anywhere.
Now my .bashrc works great.
