### ISSUE TITLE
Warnings when building 2.13.1 version

### ISSUE THREAD

**Issue by eribertomota** [eribertomota/axel#62]
On Debian Stretch, Axel 2.13.1 build produces the following warnings:

	conf.c: In function 'conf_loadfile':
	conf.c:77:3: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
	   fscanf( fp, "%100[^\n#]s", s );
	   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	conf.c:78:3: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
	   fscanf( fp, "%*[^\n]s" );
	   ^~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ordex** [comment]
I think this can be closed now. All the warning are gone :)
