### ISSUE TITLE
Axel dies saying 'Too many redirects'

### ISSUE THREAD

**Issue by eribertomota** [eribertomota/axel#7]
An example:

$ axel https://github.com/eribertomota/axel/archive/master.zip
Initializing download: https://github.com/eribertomota/axel/archive/master.zip
Too many redirects.

Is there someone able to help me with this issue?

Thanks in advance.

Regards,

Eriberto

**Comment by sijad** [comment]
I'm not sure, but I think it's related to #3
Axel tries to download from `http` but Github server forces clint to download from `https`

**Comment by eribertomota** [comment]
Hum... This is a possibility...

I will try test it soon.


2016-03-20 1:31 GMT-03:00 Sajjad Hashemian <notifications@github.com>:

**Comment by eribertomota** [comment]
Hi Sajjad,

You are right. This site[1] forces https. So, I tryed to download the index via axel ($ axel https://archive.org/details/testmp3testfile). I started a tcpdump session and I saw that axel always forces http (port 80). So, the site try to redirect to https. So, axel forces the http again. And the site forces a redirection again. It is a loop that ends in a 'Too many redirects' message.

[1] https://archive.org/details/testmp3testfile

See below the server reply (via tcpdump -A):

HTTP/1.1 301 Moved Permanently
[...]
Connection: close
Location: https://archive.org/details/testmp3testfile

So, we need a https implementation to stop the 'Too many redirects' message and to provide the https protocol to users.

We need someone able to implement this feature.

Regards,

Eriberto

**Comment by sdt** [comment]
Closing this issue as it will be fixed by #3

**Comment by NikosEfthias** [comment]
i still have this issue on ubuntu 16.4 wget successfully downloads the file from transfer.sh however on axel i get this error message

**Comment by sdt** [comment]
What version of axel do you have @NikosEfthias ?

**Comment by WilhelmErasmus** [comment]
I'm having the same problem. From what I've read, it seems that the problem has been fixed, but I think that Ubuntu probably doesn't have the latest update yet.

```
 $ axel --version

Axel version 2.5 (Linux)

Copyright 2001-2007 Wilmer van der Gaast,
          2015      Joao Eriberto Mota Filho,
                    and others.
Please, see the CREDITS file.
```

**Comment by huzhifeng** [comment]
Still exists on CentOS 7.2
```
➜  ~ rpm -q axel
axel-2.4-9.el7.x86_64
➜  ~ axel --version
Axel version 2.4 (Linux)

Copyright 2001-2002 Wilmer van der Gaast.
➜  ~ axel https://github.com/tstack/lnav/releases/download/v0.8.1/lnav-0.8.1-1.x86_64.rpm
Initializing download: https://github.com/tstack/lnav/releases/download/v0.8.1/lnav-0.8.1-1.x86_64.rpm
Too many redirects.
```

**Comment by poppingtonic** [comment]
Still exists on Arch Linux:

```bash
$ axel --version

Axel version 2.12 (Linux)

Copyright 2001-2007 Wilmer van der Gaast,
          2007-2009 Giridhar Appaji Nag,
          2008-2010 Philipp Hagemeister,
          2015-2016 Joao Eriberto Mota Filho,
          2016      Stephen Thirlwall,
                    and others.
Please, see the CREDITS file.
```

**Comment by ahmedelmahy** [comment]
still exists

**Comment by charan223** [comment]
still exists
~$ axel --version
Axel version 2.4 (Linux)

**Comment by HandsomeHans** [comment]
still exists on Ubuntu 14.04  64bit
hans@hans-HP-PC:~$ axel --version
Axel version 2.4 (Linux)

Copyright 2001-2002 Wilmer van der Gaast.

**Comment by evroza** [comment]
Still exists on ubuntu 14.04 64 bit. axel 2.4

**Comment by kcavagnolo** [comment]
Confirmed on Ubuntu 16.04.2 LTS as well:
```
[ubuntu:~] %  axel --version
Axel version 2.5 (Linux)
```

**Comment by ehye** [comment]
still in  Ubuntu 16.04.1 LTS
`axel --version

Axel version 2.5 (Linux)

Copyright 2001-2007 Wilmer van der Gaast,
          2015      Joao Eriberto Mota Filho,
                    and others.
Please, see the CREDITS file.
`

**Comment by ismaell** [comment]
Distributions have their own bug trackers, if the package is outdated it's up to the distribution to patch or upgrade it.

**Comment by QGB** [comment]
```
axel --verbose  https://d1h1zvtbgx258i.cloudfront.net/lightyear.exe
Initializing download: https://d1h1zvtbgx258i.cloudfront.net/lightyear.exe
Too many redirects.
```
curl and wget is ok

**Comment by KvistA-ELS** [comment]
I have the same issue - also with cloudfront! Browser, wget and curl doesn't get any redirects - just a 200...

**Comment by ismaell** [comment]
@KvistA-ELS could you try with a debug-enabled build of axel?

I'll try to make the output more useful for this case.
