### ISSUE TITLE
consider using libcurl

### ISSUE THREAD

**Issue by ordex** [eribertomota/axel#73]
Hello,
this question probably goes to @ismaell @eribertomota : have you guys ever considered the possibility to use libcurl directly into axel? I think this would simplify the code a lot as you won't need to deal with the "low" level http/ftp connection and can focus more on handling the data at the higher level.
Any thought?

**Comment by ismaell** [comment]
Hi @ordex,

libcurl is over 8.5x bigger; does that answer your question? 😛

I don't discard splitting axel into a library and a frontend though.

**Comment by ordex** [comment]
haha yes it does :D I'll close this ticket as it is useless
